### ISSUE TITLE
Failed to stop HttpClient threads

### ISSUE THREAD

**Issue by gomezgoiri** [RusticiSoftware/TinCanJava#38]
Since I started using this library I have experienced some __memory leaks__ in _Tomcat 7_.

When I redeploy the webapp I see some messages like the following:

    SEVERE: The web application [/analyse] appears to have started a thread named [HttpClient-82] but has failed to stop it. This is very likely to create a memory leak.

After checking _TinCanJava_, I see that you use Jetty to make HTTP requests. There is a suspicious __static private attribute__ in [RemoteLRS](https://github.com/RusticiSoftware/TinCanJava/blob/master/src/main/java/com/rusticisoftware/tincan/RemoteLRS.java) of the [HttpClient](https://wiki.eclipse.org/Jetty/Tutorial/HttpClient) class.

Is sharing a unique _HttpClient_ object a common practice for Jetty? Can this [be related](http://stackoverflow.com/questions/453023/are-static-fields-open-for-garbage-collection) to the memory leak?

I also see that _httpClient.stop()_ is not called anywhere in _RemoteLRS_. Would not be a good idea to add a method to allow us (users of _TinCanJava_) to properly close it before our application shutdowns?

Any other reason that could make _Tomcat_ not be able to stop these threads?

**Comment by brianjmiller** [comment]
You are probably correct. The PR for gzip compression (#32) started to address this issue by adjusting the thread pool handling, but based on a cursory look still doesn't seem to fully expose it via an API which is probably the best fix. I can't really speak to common practice for Jetty, but given how HttpClient is positioned, particularly with the thread setup, I suspect that yes sharing an instance is common, but as stated we probably need to expose the thread setup to the user. I can't give a timeframe on when I'll be able to get to this but if you want to take a stab and submit a pull request it will at least get the ball rolling.

**Comment by brianjmiller** [comment]
#44 should help contribute a fix for this if I understand the issue correctly. I'd still like to get the thread pool stuff in place, and based on further discussion of gzip I'm expecting the other two PRs to be closed, though I would like to capture the thread stuff from them so I'm currently leaving them open a little longer in case I can get to it in this sprint.

**Comment by gomezgoiri** [comment]
Hi Brian, thanks for letting me know. The code sent for the [issue 44](https://github.com/RusticiSoftware/TinCanJava/pull/44) definitely looks like a solution for this problem. I will use it and test it ASAP.

P.S.: Sorry for not attending you first request, I had it marked as a TODO but I never found the moment.

**Comment by gomezgoiri** [comment]
I have come back to this issue and discovered that [Jetty 8 is End of Life](https://wiki.eclipse.org/Jetty/Tutorial/HttpClient).

In [Jetty 9's HttpClient](http://download.eclipse.org/jetty/9.3.5.v20151012/apidocs/org/eclipse/jetty/client/HttpClient.html) _setThreadPool_ and _start/stop_ methods don't exist anymore.

Therefore, I was wondering whether this and other similar issues could be fixed by simply updating the Jetty dependency.

From [what I have checked](https://github.com/RusticiSoftware/TinCanJava/search?q=org.eclipse.jetty), _TinCanJava_ doesn't depend on Jetty so much. I think that it should not be so complex to make the necessary adaptations (particularly attending all the potential benefits that it could bring).

Do you want me to try this?

**Comment by gomezgoiri** [comment]
I have already updated TinCanJava [dependency to Jetty 9](https://github.com/gomezgoiri/TinCanJava/commit/111e4700a04b3fadb19ca07bf98dc3de3745cb42).

However, I won't make a pull request yet as I cannot execute all the tests successfully. This problem is independent of the changes I made so I have opened a new issue (#46).

**Comment by gomezgoiri** [comment]
The problem described in this issue can be fixed now thanks to the new [_RemoteLRS.destroy_](https://github.com/brianjmiller/TinCanJava/commit/48563f8355f04cdc9370c7915924675a71d68dc4) method. For more info see #50.

Many thanks @brianjmiller.
