### ISSUE TITLE
Initializing Statement from JSON does not auto init its id

### ISSUE THREAD

**Issue by Smedzlatko** [RusticiSoftware/TinCanJava#39]
Initializing Statement from JSON does not auto init its id even if the id is present in the JSON object.

Example:
```
StringOfJSON json = new StringOfJSON(payload); // contains id inside
Statement statement = new Statement(json);

UUID id = statement.getId(); // null
```

Correct me if I am wrong but I would expect to set the Id automatically whenever it is present in the JSON and fill in null only if it is missing.

**Comment by brianjmiller** [comment]
I've not looked to reproduce it directly, but you are correct the behavior should be that the `id` is populated. Not sure when I'll get to it, if you can find the fix and submit a PR with a unit test that'd certainly speed up the process.

**Comment by okabe-is** [comment]
I made a pull request #49 to solve this bug.

**Comment by brianjmiller** [comment]
@okabe-is thanks, merged. @Smedzlatko please test if you get a chance, I'll be cutting a release with this fix soon.
