### ISSUE TITLE
SSH Trouble with using Jetty 8.1.9

### ISSUE THREAD

**Issue by johannsell** [RusticiSoftware/TinCanJava#42]
I've got an error on communicating with a LRS behind a HTTPS Proxy. The error is the same as this one, mentioned for Jetty 8.1.9: 

<https://bugs.eclipse.org/bugs/show_bug.cgi?id=376273>

It was fixed for Jetty 8.1.10, so it would be great if the used Jetty Version could be updated.

**Comment by gomezgoiri** [comment]
In the issue #47 I refer to a couple of commits which update Jetty to 9.3.6.v20151106.

This Jetty version will probably fix your issue.

**Comment by johannsell** [comment]
Sounds cool. Currently, our system runs in production, so I can't test it up to the next update. But I will close this issue, because you've referenced to the other issue and I've tested the solution before. ;)
