### ISSUE TITLE
Etag related tests failing

### ISSUE THREAD

**Issue by gomezgoiri** [RusticiSoftware/TinCanJava#46]
When I locally execute tests using ``mvn clean test`` against a [LearningLocker](http://learninglocker.net/) LRS three of them fail:
 * _RemoteLRSTest.testOverwriteAgentProfile_
 * _RemoteLRSTest.testOverwriteState_
 * _RemoteLRSTest.testOverwriteActivityProfile_

After analysing them, they all have the following behaviour in common:
 1. They assign the Etag of another entity to a new object (a previous object is reused, but its ID and some other fields are changed)
 1. They try to create this object (using _saveAgentProfile_, _saveState_ or _saveActivityProfile_ methods). 
 1. The test fails because the server answers _HTTP 412 error_ with the content "_Precondition (If-Match) failed._"

The tests talk about overwriting/updating an object, but since the ID changes I don't think the LRS is considering that it is the same entity anymore. Therefore the Etag is not valid for that entity and IMHO __it is correct that these tests fail__.

**Comment by gomezgoiri** [comment]
I have rewritten these test to reuse the same ID and the only one which still fails is:

 * _RemoteLRSTest.testOverwriteState_

So apparently, what makes an entity for _Learning Locker_ is not only the ID but also the _activity_ associated to that object.

In fact, after reusing the same activity this test also passes successfully.

**Comment by garemoko** [comment]
@gomezgoiri there appears to be a bug in the latest version of learning locker (1.11.0) around the Agent Profile API. See https://github.com/garemoko/moodle-mod_tincanlaunch/issues/80#issuecomment-160328018

It may be worth running these tests against another LRS e.g. SCORM Cloud to confirm the problem.

**Comment by gomezgoiri** [comment]
Thanks for the clue.

Yes, all the tests pass if I use SCORM Cloud.

**Comment by brianjmiller** [comment]
I'm gathering this is resolved, re-open if necessary.
