### ISSUE TITLE
Java API Library for Java 1.7?

### ISSUE THREAD

**Issue by FrankTrog** [RusticiSoftware/TinCanJava#56]
This isn't so much an issue rather than a question or request. Is there a version of this library built with Java 1.7? We are in need of one built in 1.7 for our application we are developing.

**Comment by brianjmiller** [comment]
The 0.x series supported 1.7, but IIRC the bump to a more recent version of Jetty among other dependencies necessitated the bump to 1.8 and with 1.7 EOL'd we needed to not have it hold us back. The only changes in the public interface (so far) are related to adding Attachment support, so if you aren't needing it, then you should be okay to work on 0.9.0 and have an easy'ish transition to 1.x when you can upgrade Java. See https://github.com/RusticiSoftware/TinCanJava/releases for more info.

**Comment by FrankTrog** [comment]
Thanks Brian, we will give this a shot. I appreciate your description on the difference in versions. What exactly was the attachment support for? I would assume attaching files or something to the LRS statement but I am not quite sure how that would be achieved with the LRSs I have seen.

**Comment by brianjmiller** [comment]
See https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#attachments for information about attachments. It is a spec level thing, so a spec conforming LRS must support them.
